### ISSUE TITLE
magisk.apk是magisk.zip吗？

### ISSUE THREAD

**Issue by Frank997** [qiurigao/RMX2202#1]
你好，我在xda看到了你发的帖子，慕名而来，找到了这里，有几个问题想问一下：

1. readme文件中的magisk.apk是root所需的magisk.zip吗？

2. 如果我root了，然后通过系统更新升级，只是会丢失root还是会变砖？

3. 我现在用的系统版本是A27，是否可以通过直接刷magisk.zip root手机？

**Comment by qiurigao** [comment]
1.是
2.相当于恢复系统，不会变砖
3.任何版本都可以

**Comment by Frank997** [comment]
谢谢！

**Comment by Frank997** [comment]
> 1.是
> 2.相当于恢复系统，不会变砖
> 3.任何版本都可以

谢谢回复！
